feat(SPV-839): add requesterPaymail when adding contact
bsv-blockchain/spv-wallet-web-backend pull request #78
Opened 2024-06-24 08:27 UTC by pawellewandowski98

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet-web-backend/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet-web-backend/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

# Description

- Update `spv-wallet-go-client`. Add requester paymail when adding new contact

2024-06-24 08:47 UTC, chris-4chain approved these changes

2024-06-24 11:14 UTC, chris-4chain requested changes

2024-06-24 11:14 UTC, chris-4chain commented on go.mod
> +	github.com/bitcoin-sv/spv-wallet-go-client v1.0.0-beta.6.0.20240624072509-15fd7b1eccfe // TODO: replace with new version
Please replace it 😄

2024-06-25 07:57 UTC, pawellewandowski98 commented on go.mod
> +	github.com/bitcoin-sv/spv-wallet-go-client v1.0.0-beta.6.0.20240624072509-15fd7b1eccfe // TODO: replace with new version
Done

2024-06-25 08:15 UTC, ac4ch approved these changes
looks ok to me

2024-06-25 13:30 UTC, chris-4chain approved these changes

2024-06-25 14:00 UTC, merged